"""
AI-assisted operational briefing generation using a local Ollama LLM.
"""

import textwrap

import requests

OLLAMA_GENERATE_URL = "http://localhost:11434/api/generate"
OLLAMA_TAGS_URL = "http://localhost:11434/api/tags"
DEFAULT_MODEL = "llama3.2"
GENERATE_TIMEOUT = 180
MAX_BRIEFING_CHARS = 1800
MAX_CONTEXT_CHUNKS = 2
CONTEXT_PREVIEW_CHARS = 250

GROUNDING_NOTE = (
    "Generated from structured zone metrics and retrieved ReliefWeb/GDACS context."
)
TRANSPARENCY_NOTE = (
    "This is an AI-assisted draft generated by a local LLM. "
    "It should be reviewed before operational use."
)

OLLAMA_UNAVAILABLE_MESSAGE = (
    "Ollama is not running. Start Ollama and make sure llama3.2 is available."
)
OLLAMA_MODEL_MISSING_MESSAGE = "llama3.2 model not found. Run: ollama pull llama3.2"
OLLAMA_TIMEOUT_MESSAGE = (
    "Ollama generation timed out. Try using llama3.2, reducing retrieved context, "
    "or increasing the timeout."
)


class OllamaUnavailableError(Exception):
    """Raised when the local Ollama server cannot be reached."""


class OllamaModelNotFoundError(Exception):
    """Raised when the requested Ollama model is not installed."""


class OllamaGenerationError(Exception):
    """Raised when Ollama returns an unexpected generation response."""


def _clean(value) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _truncate(value: str, limit: int) -> str:
    cleaned = " ".join((_clean(value)).split())
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[: limit - 3] + "..."


def _format_resource_name(resource_type: str) -> str:
    if not resource_type:
        return ""
    return resource_type.replace("_", " ").title()


def _model_is_available(model: str, available_models: set[str]) -> bool:
    if model in available_models:
        return True
    return any(name.startswith(f"{model}:") or name == model for name in available_models)


def ensure_ollama_model(model: str = DEFAULT_MODEL) -> None:
    """Verify the local Ollama server is reachable and the requested model is installed."""
    try:
        response = requests.get(OLLAMA_TAGS_URL, timeout=5)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise OllamaUnavailableError(f"{OLLAMA_UNAVAILABLE_MESSAGE} Details: {exc}") from exc

    models = response.json().get("models", [])
    available = {item.get("name", "") for item in models if item.get("name")}
    if not _model_is_available(model, available):
        if model == DEFAULT_MODEL:
            raise OllamaModelNotFoundError(OLLAMA_MODEL_MISSING_MESSAGE)
        raise OllamaModelNotFoundError(
            f"{model} model not found. Run: ollama pull {model}"
        )


def _format_priority_needs(priority_needs: list) -> str:
    if not priority_needs:
        return "None recorded."

    lines: list[str] = []
    for need in priority_needs[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(need.get('resource_type')))}: "
            f"gap {_clean(need.get('shortage_gap')) or '—'}, "
            f"{_clean(need.get('status_label')) or '—'}"
        )
    return "\n".join(lines)


def _format_inventory(inventory: list) -> str:
    if not inventory:
        return "None recorded."

    lines: list[str] = []
    for item in inventory[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(item.get('resource_type')))}: "
            f"{_clean(item.get('quantity_available')) or '—'} {_clean(item.get('unit')) or 'units'}"
        )
    return "\n".join(lines)


def _format_requests(requests_list: list) -> str:
    if not requests_list:
        return "None recorded."

    lines: list[str] = []
    for item in requests_list[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(item.get('resource_type')))}: "
            f"needed {_clean(item.get('quantity_needed')) or '—'}, "
            f"{_clean(item.get('urgency_level')) or '—'}"
        )
    return "\n".join(lines)


def _format_related_alert(related_alert: dict | None) -> str:
    if not related_alert:
        return "No directly linked primary GDACS alert is available for this zone."

    parts = [
        f"Title: {_truncate(related_alert.get('title'), 160)}",
        f"Event: {_clean(related_alert.get('event_type')) or '—'}",
        f"Severity: {_clean(related_alert.get('severity_color')) or '—'}",
    ]
    description = _truncate(related_alert.get("description"), 300)
    if description:
        parts.append(f"Description: {description}")
    return " | ".join(parts)


def _has_fallback_context(retrieved_context: list) -> bool:
    return any(item.get("is_fallback") is True for item in retrieved_context)


def _format_retrieved_context(
    retrieved_context: list,
    rag_unavailable: bool,
    has_fallback_context: bool = False,
) -> str:
    if rag_unavailable:
        return "Unavailable. Use structured metrics and primary alert only."

    if not retrieved_context:
        return "None found."

    lines: list[str] = ["Supporting evidence only. Do not use as the primary event."]
    country_specific = 0

    for index, item in enumerate(retrieved_context[:MAX_CONTEXT_CHUNKS], start=1):
        is_fallback = item.get("is_fallback") is True
        if not is_fallback:
            country_specific += 1

        title = _truncate(item.get("title"), 120)
        source_type = _clean(item.get("source_type")) or "unknown source"
        country = _clean(item.get("country")) or "—"
        event_type = _clean(item.get("event_type")) or "—"
        context_label = "fallback/general context" if is_fallback else "country-specific"
        preview = _truncate(item.get("preview") or item.get("chunk_text"), CONTEXT_PREVIEW_CHARS)

        lines.append(
            f"{index}. {source_type} record ({context_label}): "
            f"\"{title}\" — {country}, {event_type}. Summary: {preview}"
        )

    if has_fallback_context:
        lines.append(
            "Some retrieved sources are fallback context and should not be treated as "
            "direct evidence for the selected country."
        )
    elif country_specific:
        lines.append("All retrieved sources provided to the model are country-specific supporting context.")

    return "\n".join(lines)


def _format_source_types_label(retrieved_context: list) -> str:
    labels: list[str] = []
    for item in retrieved_context:
        source_type = _clean(item.get("source_type")).lower()
        if source_type == "gdacs" and "GDACS" not in labels:
            labels.append("GDACS")
        elif source_type == "reliefweb" and "ReliefWeb" not in labels:
            labels.append("ReliefWeb")
    if not labels:
        return "ReliefWeb/GDACS"
    return "/".join(labels)


def _resolve_event_type(related_alert: dict | None, retrieved_context: list) -> str:
    if related_alert and _clean(related_alert.get("event_type")):
        return _clean(related_alert.get("event_type"))

    country_specific_events = [
        _clean(item.get("event_type"))
        for item in retrieved_context
        if not item.get("is_fallback") and _clean(item.get("event_type"))
    ]
    if country_specific_events:
        return max(set(country_specific_events), key=country_specific_events.count)

    fallback_events = [
        _clean(item.get("event_type"))
        for item in retrieved_context
        if _clean(item.get("event_type"))
    ]
    if fallback_events:
        return max(set(fallback_events), key=fallback_events.count)
    return ""


def build_retrieved_context_summary(
    zone: dict,
    related_alert: dict | None,
    retrieved_context: list,
    has_fallback_context: bool,
    rag_unavailable: bool = False,
) -> str:
    """Build a zone-specific retrieved context summary for the LLM prompt."""
    country = _clean(zone.get("country")) or "the selected zone"

    if rag_unavailable:
        return (
            "Retrieved context is unavailable. Use structured zone metrics and the primary "
            "alert rule below only."
        )

    if not retrieved_context:
        if related_alert:
            return (
                f"No retrieved ReliefWeb/GDACS records were found for {country}. "
                "Use the primary related alert as the main event."
            )
        return (
            f"No retrieved ReliefWeb/GDACS records were found for {country}. "
            "No directly linked primary GDACS alert is available for this zone."
        )

    source_label = _format_source_types_label(retrieved_context)
    event_type = _resolve_event_type(related_alert, retrieved_context)
    lines: list[str] = []

    if related_alert:
        alert_title = _truncate(related_alert.get("title"), 120)
        alert_event = _clean(related_alert.get("event_type")) or "unspecified event type"
        lines.append(
            f"Primary related alert: {alert_title} ({alert_event})."
        )
    else:
        lines.append("No directly linked primary GDACS alert is available for this zone.")

    if event_type:
        lines.append(
            f"Country-specific {source_label} records include {country} {event_type} context "
            "relevant to the selected zone."
        )
    else:
        lines.append(
            f"Retrieved {source_label} context includes available {country} records relevant "
            "to the selected zone."
        )

    lines.append(
        "Retrieved context supports situational awareness but does not replace the primary alert."
    )

    if has_fallback_context:
        lines.append(
            "Some retrieved sources are fallback context and should not be treated as direct "
            "evidence for the selected country."
        )
    else:
        lines.append("Retrieved sources are country-specific supporting context.")

    return " ".join(lines)


def _retrieved_context_prompt_rules(retrieved_context_summary: str) -> str:
    return textwrap.dedent(
        f"""
        Retrieved Crisis Context section rules:
        - Use at most 3 short bullets in this section only.
        - Do not include long quoted source titles.
        - Use the provided retrieved_context_summary as the basis for this section.
        - Retrieved context summary: {retrieved_context_summary}
        - Do not mention another country or event type unless it appears in the selected zone or retrieved context.
        - Do not reuse example wording from other zones.
        - Do not say Philippines unless the selected country is Philippines or a retrieved source is explicitly from Philippines.
        - Do not say earthquake unless the primary alert or retrieved context event type is earthquake.
        - Retrieved context supports situational awareness but does not replace the primary alert.
        """
    ).strip()


def _situation_prompt_rules(
    related_alert: dict | None,
    zone_name: str,
    country: str,
) -> str:
    if related_alert:
        return textwrap.dedent(
            """
            Situation section rules:
            - Use the related alert title, event, severity, and description as the PRIMARY event.
            - The selected related alert is the main event in Situation.
            """
        ).strip()

    return textwrap.dedent(
        f"""
        Situation section rules:
        - Include the selected zone name and country.
        - Say only: "No directly linked primary GDACS alert is available for this zone."
        - Do not infer that response efforts are absent.
        - Do not infer that the situation is low priority just because no alert is linked.
        - Do not say "lack of immediate disaster response efforts."
        - Resource gaps still matter even if no primary alert is linked.
        - State that current operational concern is based on resource gaps and retrieved context.
        - Example style: "The {zone_name} in {country} has no directly linked primary GDACS alert. Current operational concern is based on identified resource gaps and retrieved ReliefWeb/GDACS context."
        """
    ).strip()


def build_ai_briefing_prompt(
    zone: dict,
    priority_needs: list,
    inventory: list,
    requests_list: list,
    related_alert: dict | None,
    retrieved_context: list,
    rag_unavailable: bool = False,
) -> str:
    """Build the grounded prompt for local Ollama operational briefing generation."""
    zone_name = _clean(zone.get("zone_name")) or "Unknown Zone"
    country = _clean(zone.get("country")) or "—"
    admin_region = _clean(zone.get("admin_region")) or "—"
    population = _clean(zone.get("population_estimate")) or "—"
    context_items = retrieved_context[:MAX_CONTEXT_CHUNKS]
    has_fallback_context = _has_fallback_context(context_items)
    retrieved_context_summary = build_retrieved_context_summary(
        zone=zone,
        related_alert=related_alert,
        retrieved_context=context_items,
        has_fallback_context=has_fallback_context,
        rag_unavailable=rag_unavailable,
    )
    retrieved_context_rules = _retrieved_context_prompt_rules(retrieved_context_summary)
    situation_rules = _situation_prompt_rules(related_alert, zone_name, country)
    primary_alert_rule = (
        "The selected related alert is the PRIMARY event in Situation."
        if related_alert
        else (
            "No directly linked primary GDACS alert is available for this zone. "
            "Do not infer absent response efforts or low priority. Resource gaps still matter."
        )
    )

    return textwrap.dedent(
        f"""
        Write a concise operational briefing using only the data below.

        Output format:
        - Use exactly 5 sections with these headings only:
        ### Situation
        ### Priority Resource Gaps
        ### Retrieved Crisis Context
        ### Recommended Actions
        ### Limitations
        - Use maximum 2 bullets per section (Retrieved Crisis Context may use up to 3 per its rules).
        - Do not use nested bullets or tabs.
        - Keep each bullet under 25 words.
        - Do not add a document title or duplicate headings.
        - Complete all five sections. Finish the Limitations section fully.

        Grounding rules:
        - {primary_alert_rule}
        - If no related alert exists, say only that no directly linked primary GDACS alert is available for this zone.
        - Do not infer that response efforts are absent.
        - Do not infer that the situation is low priority just because no alert is linked.
        - Do not say "lack of immediate disaster response efforts."
        - Resource gaps still matter even if no primary alert is linked.
        - Retrieved context is supporting evidence only; do not replace the primary event.
        - Use the provided retrieved_context_summary in Retrieved Crisis Context.
        - Do not mention another country or event type unless it appears in the selected zone or retrieved context.
        - Preserve source dates exactly as provided (e.g. keep 08/06/2026 as 08/06/2026).
        - Use only the provided information. Do not invent facts.
        - Do not output raw metadata, JSON, or key=value fields.

        {situation_rules}

        {retrieved_context_rules}

        Limitations section rules:
        - Use exactly these 2 bullets and no others:
        - Operational inventory and request data are simulated prototype data.
        - Retrieved context is limited to available ReliefWeb/GDACS records, and the AI draft should be reviewed before operational use.
        - Do not discuss missing population data unless explicitly asked.
        - Do not claim affected population data is unavailable.
        - Do not add new limitations beyond the provided limitations.

        Zone: {zone_name}
        Location: {country}, {admin_region}
        Population estimate: {population}

        PRIMARY RELATED ALERT (use this as the main event in Situation):
        {_format_related_alert(related_alert)}

        Priority needs:
        {_format_priority_needs(priority_needs)}

        Inventory:
        {_format_inventory(inventory)}

        Requests:
        {_format_requests(requests_list)}

        SUPPORTING RETRIEVED CONTEXT (supporting evidence only):
        {_format_retrieved_context(context_items, rag_unavailable, has_fallback_context)}

        RETRIEVED CONTEXT SUMMARY (use this in Retrieved Crisis Context):
        {retrieved_context_summary}
        Fallback context present: {str(has_fallback_context).lower()}
        """
    ).strip()


def _call_ollama_generate(prompt: str, model: str = DEFAULT_MODEL) -> str:
    """Call Ollama /api/generate and return the briefing text."""
    try:
        response = requests.post(
            OLLAMA_GENERATE_URL,
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.2,
                    "num_predict": 450,
                },
            },
            timeout=GENERATE_TIMEOUT,
        )
        response.raise_for_status()
    except requests.ConnectionError as exc:
        raise OllamaUnavailableError(OLLAMA_UNAVAILABLE_MESSAGE) from exc
    except requests.Timeout as exc:
        raise OllamaUnavailableError(OLLAMA_TIMEOUT_MESSAGE) from exc
    except requests.RequestException as exc:
        message = str(exc)
        if "404" in message or "not found" in message.lower():
            raise OllamaModelNotFoundError(OLLAMA_MODEL_MISSING_MESSAGE) from exc
        raise OllamaUnavailableError(f"{OLLAMA_UNAVAILABLE_MESSAGE} Details: {exc}") from exc

    payload = response.json()
    briefing_text = _clean(payload.get("response"))
    if not briefing_text:
        raise OllamaGenerationError("Ollama returned an empty briefing response.")

    if len(briefing_text) > MAX_BRIEFING_CHARS:
        briefing_text = briefing_text[: MAX_BRIEFING_CHARS - 3].rstrip() + "..."
    return briefing_text


def generate_ai_operational_brief(
    zone: dict,
    priority_needs: list,
    inventory: list,
    requests_list: list,
    related_alert: dict | None,
    retrieved_context: list,
    model: str = DEFAULT_MODEL,
    rag_unavailable: bool = False,
) -> dict:
    """Generate an AI-assisted operational briefing grounded in zone metrics and RAG context."""
    ensure_ollama_model(model)
    prompt = build_ai_briefing_prompt(
        zone=zone,
        priority_needs=priority_needs,
        inventory=inventory,
        requests_list=requests_list,
        related_alert=related_alert,
        retrieved_context=retrieved_context[:MAX_CONTEXT_CHUNKS],
        rag_unavailable=rag_unavailable,
    )
    briefing_text = _call_ollama_generate(prompt, model=model)

    return {
        "model": model,
        "briefing_text": briefing_text,
        "generation_type": "ollama_local_llm",
        "grounding_note": GROUNDING_NOTE,
        "transparency_note": TRANSPARENCY_NOTE,
    }
