"""
AI-assisted operational briefing generation using a local Ollama LLM.
"""

import textwrap

import requests

OLLAMA_GENERATE_URL = "http://localhost:11434/api/generate"
OLLAMA_TAGS_URL = "http://localhost:11434/api/tags"
DEFAULT_MODEL = "llama3.2"
GENERATE_TIMEOUT = 180
MAX_BRIEFING_CHARS = 1500
MAX_CONTEXT_CHUNKS = 2
CONTEXT_PREVIEW_CHARS = 250

GROUNDING_NOTE = (
    "Generated from structured zone metrics and retrieved ReliefWeb/GDACS context."
)
TRANSPARENCY_NOTE = (
    "This is an AI-assisted draft generated by a local LLM. "
    "It should be reviewed before operational use."
)

OLLAMA_UNAVAILABLE_MESSAGE = (
    "Ollama is not running. Start Ollama and make sure llama3.2 is available."
)
OLLAMA_MODEL_MISSING_MESSAGE = "llama3.2 model not found. Run: ollama pull llama3.2"
OLLAMA_TIMEOUT_MESSAGE = (
    "Ollama generation timed out. Try using llama3.2, reducing retrieved context, "
    "or increasing the timeout."
)


class OllamaUnavailableError(Exception):
    """Raised when the local Ollama server cannot be reached."""


class OllamaModelNotFoundError(Exception):
    """Raised when the requested Ollama model is not installed."""


class OllamaGenerationError(Exception):
    """Raised when Ollama returns an unexpected generation response."""


def _clean(value) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _truncate(value: str, limit: int) -> str:
    cleaned = " ".join((_clean(value)).split())
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[: limit - 3] + "..."


def _format_resource_name(resource_type: str) -> str:
    if not resource_type:
        return ""
    return resource_type.replace("_", " ").title()


def _model_is_available(model: str, available_models: set[str]) -> bool:
    if model in available_models:
        return True
    return any(name.startswith(f"{model}:") or name == model for name in available_models)


def ensure_ollama_model(model: str = DEFAULT_MODEL) -> None:
    try:
        response = requests.get(OLLAMA_TAGS_URL, timeout=5)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise OllamaUnavailableError(f"{OLLAMA_UNAVAILABLE_MESSAGE} Details: {exc}") from exc

    models = response.json().get("models", [])
    available = {item.get("name", "") for item in models if item.get("name")}
    if not _model_is_available(model, available):
        if model == DEFAULT_MODEL:
            raise OllamaModelNotFoundError(OLLAMA_MODEL_MISSING_MESSAGE)
        raise OllamaModelNotFoundError(
            f"{model} model not found. Run: ollama pull {model}"
        )


def _format_priority_needs(priority_needs: list) -> str:
    if not priority_needs:
        return "None recorded."

    lines: list[str] = []
    for need in priority_needs[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(need.get('resource_type')))}: "
            f"gap {_clean(need.get('shortage_gap')) or '—'}, "
            f"{_clean(need.get('status_label')) or '—'}"
        )
    return "\n".join(lines)


def _format_inventory(inventory: list) -> str:
    if not inventory:
        return "None recorded."

    lines: list[str] = []
    for item in inventory[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(item.get('resource_type')))}: "
            f"{_clean(item.get('quantity_available')) or '—'} {_clean(item.get('unit')) or 'units'}"
        )
    return "\n".join(lines)


def _format_requests(requests_list: list) -> str:
    if not requests_list:
        return "None recorded."

    lines: list[str] = []
    for item in requests_list[:3]:
        lines.append(
            "- "
            f"{_format_resource_name(_clean(item.get('resource_type')))}: "
            f"needed {_clean(item.get('quantity_needed')) or '—'}, "
            f"{_clean(item.get('urgency_level')) or '—'}"
        )
    return "\n".join(lines)


def _format_related_alert(related_alert: dict | None) -> str:
    if not related_alert:
        return "None linked."

    return (
        f"Title: {_truncate(related_alert.get('title'), 120)} | "
        f"Event: {_clean(related_alert.get('event_type')) or '—'} | "
        f"Severity: {_clean(related_alert.get('severity_color')) or '—'}"
    )


def _format_retrieved_context(retrieved_context: list, rag_unavailable: bool) -> str:
    if rag_unavailable:
        return "Unavailable. Use structured metrics only."

    if not retrieved_context:
        return "None found."

    lines: list[str] = []
    for index, item in enumerate(retrieved_context[:MAX_CONTEXT_CHUNKS], start=1):
        preview = _truncate(item.get("preview") or item.get("chunk_text"), CONTEXT_PREVIEW_CHARS)
        lines.append(
            f"{index}. title={_truncate(item.get('title'), 120)}; "
            f"source={_clean(item.get('source_type')) or '—'}; "
            f"country={_clean(item.get('country')) or '—'}; "
            f"event={_clean(item.get('event_type')) or '—'}; "
            f"fallback={bool(item.get('is_fallback'))}; "
            f"preview={preview}"
        )
    return "\n".join(lines)


def build_ai_briefing_prompt(
    zone: dict,
    priority_needs: list,
    inventory: list,
    requests_list: list,
    related_alert: dict | None,
    retrieved_context: list,
    rag_unavailable: bool = False,
) -> str:
    zone_name = _clean(zone.get("zone_name")) or "Unknown Zone"
    country = _clean(zone.get("country")) or "—"
    admin_region = _clean(zone.get("admin_region")) or "—"

    return textwrap.dedent(
        f"""
        Write a concise operational briefing for humanitarian coordination.

        Rules:
        - Write a concise operational briefing in 5 short bullet points.
        - Do not exceed 180 words.
        - Use only the provided information.
        - Do not invent facts.
        - If retrieved context is limited or fallback, state that.
        - Use exact source wording for dates, times, event titles, and severity levels.
        - Do not reinterpret ambiguous dates.
        - Preserve dates exactly as provided in the source text.
        - If a date appears as 08/06/2026, keep it as 08/06/2026 instead of converting it to a month name.
        - Do not infer month/day order unless explicitly provided.

        Sections:
        - Situation
        - Priority Gaps
        - Retrieved Context
        - Recommended Actions
        - Limitations

        Limitations section rules:
        - Do not claim population or affected-area information is unavailable if it is provided in the prompt.
        - Mention that operational inventory and request data are simulated prototype data.
        - Mention that retrieved context is limited to available ReliefWeb/GDACS records.
        - Mention that this AI output is a draft and should be reviewed before operational use.
        - Avoid vague limitations such as "limited information on affected areas" unless that is explicitly true from the provided data.

        Zone: {zone_name}
        Location: {country}, {admin_region}
        Alert: {_format_related_alert(related_alert)}
        Priority needs:
        {_format_priority_needs(priority_needs)}
        Inventory:
        {_format_inventory(inventory)}
        Requests:
        {_format_requests(requests_list)}
        Retrieved context:
        {_format_retrieved_context(retrieved_context, rag_unavailable)}
        """
    ).strip()


def _call_ollama_generate(prompt: str, model: str = DEFAULT_MODEL) -> str:
    try:
        response = requests.post(
            OLLAMA_GENERATE_URL,
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.2,
                    "num_predict": 220,
                },
            },
            timeout=GENERATE_TIMEOUT,
        )
        response.raise_for_status()
    except requests.ConnectionError as exc:
        raise OllamaUnavailableError(OLLAMA_UNAVAILABLE_MESSAGE) from exc
    except requests.Timeout as exc:
        raise OllamaUnavailableError(OLLAMA_TIMEOUT_MESSAGE) from exc
    except requests.RequestException as exc:
        message = str(exc)
        if "404" in message or "not found" in message.lower():
            raise OllamaModelNotFoundError(OLLAMA_MODEL_MISSING_MESSAGE) from exc
        raise OllamaUnavailableError(f"{OLLAMA_UNAVAILABLE_MESSAGE} Details: {exc}") from exc

    payload = response.json()
    briefing_text = _clean(payload.get("response"))
    if not briefing_text:
        raise OllamaGenerationError("Ollama returned an empty briefing response.")

    if len(briefing_text) > MAX_BRIEFING_CHARS:
        briefing_text = briefing_text[: MAX_BRIEFING_CHARS - 3].rstrip() + "..."
    return briefing_text


def generate_ai_operational_brief(
    zone: dict,
    priority_needs: list,
    inventory: list,
    requests_list: list,
    related_alert: dict | None,
    retrieved_context: list,
    model: str = DEFAULT_MODEL,
    rag_unavailable: bool = False,
) -> dict:
    """Generate an AI-assisted operational briefing grounded in zone metrics and RAG context."""
    ensure_ollama_model(model)
    prompt = build_ai_briefing_prompt(
        zone=zone,
        priority_needs=priority_needs,
        inventory=inventory,
        requests_list=requests_list,
        related_alert=related_alert,
        retrieved_context=retrieved_context[:MAX_CONTEXT_CHUNKS],
        rag_unavailable=rag_unavailable,
    )
    briefing_text = _call_ollama_generate(prompt, model=model)

    return {
        "model": model,
        "briefing_text": briefing_text,
        "generation_type": "ollama_local_llm",
        "grounding_note": GROUNDING_NOTE,
        "transparency_note": TRANSPARENCY_NOTE,
    }
